goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.array', 'goog.object', 'goog.string.StringBuffer']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['cljs.core', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency("../tesseract/dom.js", ['tesseract.dom'], ['cljs.core', 'clojure.string']);
goog.addDependency("../tesseract/queue.js", ['tesseract.queue'], ['cljs.core']);
goog.addDependency("../tesseract/mount.js", ['tesseract.mount'], ['cljs.core']);
goog.addDependency("../tesseract/component.js", ['tesseract.component'], ['cljs.core', 'tesseract.dom']);
goog.addDependency("../tesseract/core.js", ['tesseract.core'], ['tesseract.queue', 'cljs.core', 'tesseract.mount', 'tesseract.dom', 'tesseract.component']);
goog.addDependency("../examples/basic/core.js", ['examples.basic.core'], ['cljs.core', 'tesseract.dom', 'tesseract.core']);
goog.addDependency("../tesseract/update_queue.js", ['tesseract.update_queue'], ['cljs.core']);
goog.addDependency("../clojure/set.js", ['clojure.set'], ['cljs.core']);
goog.addDependency("../tesseract/attrs.js", ['tesseract.attrs'], ['cljs.core', 'tesseract.dom', 'clojure.set']);